[toolchain]
# most recently nightly that works with galactic-unicorn before this issue:
# https://github.com/embassy-rs/embassy/issues/3078
channel = "nightly-2024-06-12"
components = [
  "cargo",
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rust-src",
  "rustfmt",
]
targets = [
  "thumbv6m-none-eabi",
]
profile = "minimal"
