[toolchain]
channel = "nightly-2024-06-12"
components = [
  "cargo",
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rust-src",
  "rustfmt",
]
targets = [
  "thumbv6m-none-eabi",
]
profile = "minimal"
